Class {
	#name : #StReporter,
	#superclass : #Object,
	#category : #'SmallTest-Core'
}

{ #category : #'as yet unclassified' }
StReporter >> caseEnded: aTestCase withResult: testResult [
]

{ #category : #'as yet unclassified' }
StReporter >> caseStarting: aTestCase [
]

{ #category : #'as yet unclassified' }
StReporter >> planEnded: aTestPlan [
]

{ #category : #'as yet unclassified' }
StReporter >> planStarting: aTestPlan [
]

{ #category : #'as yet unclassified' }
StReporter >> suiteEnded: aTestSuite [
]

{ #category : #'as yet unclassified' }
StReporter >> suiteStarting: aTestSuite [
]
